### ISSUE TITLE
Feature Request: Assign tb as a shorthand to \textbf 

### ISSUE THREAD

**Issue by thelastindian** [joeyuping/quick_latex_obsidian#102]
te{and then space} will give me text{}

Please update  the project so that tb{and then space} will give up \textbf{}

https://github.com/joeyuping/quick_latex_obsidian/assets/105973016/d178d9ec-762f-47ad-878e-d571ebf50096

edit: I just realized you can add custom shortcuts, but nevertheless, I think this would be a good addition by default 

https://github.com/joeyuping/quick_latex_obsidian/assets/105973016/724f5525-149d-4d1b-9985-70373a3dae60

https://imgur.com/a/TBUqzff If the above video doesn't work.

**Comment by joeyuping** [comment]
@thelastindian 
hi !

this can be done in the plugin settings page, at the bottom, there is a large textbox to customize your own shorthand. The syntax is described in the description.

**Comment by thelastindian** [comment]
> this can be done in the plugin settings page, at the bottom, there is a large textbox to customize your own shorthand. The syntax is described in the description.

hey thank you! I found that out almost at the same time as you commented that. 
Be that as it may, maybe this would be a good by default?

**Comment by thelastindian** [comment]
I am closing the issue, give a thought about maybe including it in the default! Appreciate the work you are doing! Thanks!
