### ISSUE TITLE
Random insertions of & within align block

### ISSUE THREAD

**Issue by 3f6a** [joeyuping/quick_latex_obsidian#103]
When within an aligned equation:

```
$$
\begin{align*}
...
\end{align*}
$$
```

Pressing spacebar sometimes results in insertion of `&`. I'm not sure exactly what triggers it, but the `&` appear in random locations, even inside other commands such as a `\frac` inside the aligned equation. Note that I have disabled the "Auto-align at these symbols options" (by leaving the list of symbols empty).

<img width="787" alt="Screenshot 2023-08-29 at 23 48 11" src="https://github.com/joeyuping/quick_latex_obsidian/assets/126961207/f0421b0f-cba6-4ad0-b244-2319f472f7bc">

**Comment by joeyuping** [comment]
Hi ! @3f6a 

Thank you so much for bringing up this bug! This is resolved in v2.6.3
