### ISSUE TITLE
Shorthand problem

### ISSUE THREAD

**Issue by joezhouchenye** [joeyuping/quick_latex_obsidian#11]
For example, type De and space, it becomes \Delta, but if I type space again, it becomes \Del \tau.

**Comment by joeyuping** [comment]
ah thank you!! because the "ta" at the end of "delta" happens to also be the shorthand for "tau". That would indeed be an issue ... I will look into it asap!

**Comment by joeyuping** [comment]
hi ! @joezhouchenye 

Thank you so much for bringing up this bug. I resolved the issue by keeping a space after the greek letter expression. 

Also, I took the chance to add another function:  for custom shorthand expression ending with {}, cursor will be placed within the {} bracket. eg. type sq followed by space will replace with \sqrt{} and put cursor within the brackets. 

Please see version 1.5.1 and help me test if everything should be working as expected now~ thanks!
