### ISSUE TITLE
\frac from / not working properly with functions

### ISSUE THREAD

**Issue by d4vidyo** [joeyuping/quick_latex_obsidian#129]
When i write $ f(x)/x $ and press Space it should convert to $ \frac{f(x)}{x} $ however it always gives me $ f\frac{x}{x} $.

**Comment by jvsteiner** [comment]
I suggest to use $(f(x))/x$ in such situations - I think the existing functionality is correct, otherwise it's not clear what should be in the numerator.

**Comment by d4vidyo** [comment]
I see... though i think using `{ }` instead of `( )` would make more sense.
Anyway i found using a Shorthand for fractions works better for me so this isnt an issue anymore.
