### ISSUE TITLE
Minor issue with \limits auto-fill

### ISSUE THREAD

**Issue by infinityiowastaken** [joeyuping/quick_latex_obsidian#13]
https://github.com/joeyuping/quick_latex_obsidian/blob/a1fa65f51ade718b66691d04bb71620d56888875/main.ts#L401

Because the auto-replace does not test for the `\` before the sum, it will trigger when typing the word sum in another context - for example, trying to type `\text{sum` will lead to `\limits` being auto-inserted

Thanks!

**Comment by joeyuping** [comment]
thank you!! I have resolved this in 1.5.2
