### ISSUE TITLE
Shorthand not working at the beginning of line

### ISSUE THREAD

**Issue by Nemoos-0** [joeyuping/quick_latex_obsidian#16]
In a math block written like so

```
$$
de 
$$
```

`de` does not get expanded to `\delta`, but if I put a space before `de` it works fine

```
$$
 \delta
$$
```

Is it possible to make new line an allowed character to put before shorthand?

Thanks for the amazing plugin, it saved me ages 😄.

**Comment by joeyuping** [comment]
oh no !! thank you for bringing this up!! will look into it asap.

**Comment by joeyuping** [comment]
Thank you! I have resolved this issue in version 1.5.4~
