### ISSUE TITLE
Can't add space after shorthand

### ISSUE THREAD

**Issue by Nemoos-0** [joeyuping/quick_latex_obsidian#17]
When the shorthand is the same as the expanded text (ex: `pi:\pi`) it is not possible to add a space after it.
For example if you press space after `\pi` it will do nothing.

I have no idea on how to solve this; since the `\` detection is very useful when you write something like `\de ` -> `\delta`, hopefully you can come up with a better solution.

Thanks.

**Comment by joeyuping** [comment]
Thank you !!

I noticed this issue only happens for the case of \pi or such two-letter expression, where the expression itself is basically the same as the shorthand (may be only without the \ symbol), so it becomes an infinite loop where the system continuously replace the shorthand with the expression which is basically the same as the shorthand. 

I have resolved this issue to check for such a case and ignore the command when that happen. Please check out version 1.5.4 and see if it all work as expected now~

**Comment by Nemoos-0** [comment]
It works perfectly. Thanks for the super fast fix.
