### ISSUE TITLE
Auto bracket-enlargement error

### ISSUE THREAD

**Issue by richukuttan** [joeyuping/quick_latex_obsidian#18]
Hi,

If I try to change `$$(\frac{a}{b})+(c)$$` to `$$\left(\frac{a}{b}\right)+(c)$$`, I get `$$\left(\frac{a}{b})+(c\right)$$` instead. I guess you need some logic to find out which is the closing bracket corresponding to the opening bracket I'm trying to enlarge.

Thanks for your plugin! It makes my latex work so much easier!

**Comment by joeyuping** [comment]
Thank you!! I have resolved this in v 1.5.5, see i its OK ~
