### ISSUE TITLE
Suggestion: Option to auto-close $$ blocks

### ISSUE THREAD

**Issue by infinityiowastaken** [joeyuping/quick_latex_obsidian#2]
Would it be possible to implement an auto-close system for the $ sign in a similar way to brackets and quotes, such that pressing `$` once would lead to two dollar signs being added to the page with the cursor placed between them, and pressing `$` then `$` again would lead to four signs added?

(also thank you so much for making this project, it's amazing!)

**Comment by joeyuping** [comment]
I have added the autoCloseMath function onto the plugin (version 1.3.1) ! Please try updating plugins and take a look. @infinityiowastaken
