### ISSUE TITLE
Live Preview Mode

### ISSUE THREAD

**Issue by richukuttan** [joeyuping/quick_latex_obsidian#20]
Hi,

The plugin does not work when live preview is on - even for inline latex which is not previewed live.

The live preview is experimental and depends on a new version of CodeMirror, so it is understandable that the same plugin may not work for the new version, but I'm actively using this feature and really miss the functionality provided by your plugin.

Looking forward to using it in live preview mode too!

**Comment by infinityiowastaken** [comment]
Have you tried [codemirror options](https://github.com/nothingislost/obsidian-codemirror-options)?

This enables some of the live preview features on the 'classic' mode without breaking this plugin

**Comment by joeyuping** [comment]
@infinityiowastaken  thank you so much, I was about to suggest the same thing too ! XD 

@richukuttan thank you so much for bringing up this issue! I have gotten my copy of Catalyst and the insider build, and varified the issue too. 
Indeed, it seems like a big change in the backend CodeMirror, which I suppose might really take some time to figure out what was the actual issue... 
It might really take me a long while to work it out. In the mean time, as suggested by @infinityiowastaken, the codemirror options plugin does do a great job in creating this WYSIWYG editor environment and latex preview without breaking the quick latex plugin. :)

**Comment by richukuttan** [comment]
That's a sweet plugin that I was never aware of. To think that I could have been enjoying live preview from almost 6 months back :(

Anyway, @infinityiowastaken, thanks for alerting me to this option. I'll try disabling Obsidian's builtin live preview and using this plugin!

@joeyuping, the plugin recommends switching over to the Obsidian builtin once it becomes stable, so I hope that by the time a general (non-catalyst) WYSIWYG obsidian build is ready (which'll probably take months), the plugin is ready for the switch.

Thanks again to both of you!
