### ISSUE TITLE
Align fatal error

### ISSUE THREAD

**Issue by Nemoos-0** [joeyuping/quick_latex_obsidian#22]
Version 2.1.0

In preview mode

```
$$
\begin{align*}
x = \frac{1}{2}\\\
&=
\end{align*}
$$
```

Putting the cursor after `&=` in the second line of the align block and pressing Space completely block obsidian and send the CPU to 100% load (it could be an infinite loop). After that I am not even able to close the app or interact with it in any way.

Even just by doing

```
$$
\\

$$
```

as soon as I press the Space key in the new line it breaks, but if I put a space after the `\\ ` it works fine. 

The error does not occur in legacy mode.

Hope this can be useful.
Thanks for the live preview update.

**Comment by joeyuping** [comment]
thank you, thank you so much! I resolved it with update v2.1.1  @Nemoos-0
