### ISSUE TITLE
\in and \infty

### ISSUE THREAD

**Issue by smerkousdavid** [joeyuping/quick_latex_obsidian#26]
I use a lot of set notation and have noticed every time I want to do something like 
x \in \{0, 1\} for example that after typing \in it autocompletes to \infty. I love the autocomplete but maybe \in should not be completed to infty as it causes more issues than it fixes. Maybe there is a better work around?

**Comment by smerkousdavid** [comment]
Nevermind I found the custom shorthand parameter setting and was able to remove them! Apologies for the extra issue.

**Comment by joeyuping** [comment]
@smerkousdavid thank you so much for bringing up this issue!! I forgot about the presence of \in.  

I have removed in:\infty from the next release.
