### ISSUE TITLE
Not able to install plugin

### ISSUE THREAD

**Issue by MysticMaestro** [joeyuping/quick_latex_obsidian#29]
I had version 2.1.3 installed and I saw that an update 2.1.4 was available but it said "failed to update.." So I thought I will reinstall the plugin and now I am not able to install the plugin at all. Any solution? This plugin has become very important for me and I would really appreciate a solution

**Comment by Thensley365** [comment]
Having the same issue. Prior to 2.1.4 this was genius. Please advise

**Comment by joeyuping** [comment]
I am terribly sorry!! I have resolved the issue. Please update again and see if all is well.

So sorry again! @MysticMaestro @Thensley365

**Comment by samuelwebb2** [comment]
Thank you so much!
