### ISSUE TITLE
autocomplete {}

### ISSUE THREAD

**Issue by Fl1tzi** [joeyuping/quick_latex_obsidian#3]
Hey I honestly didn't really looked into your programming but what about an autocomplete feature for : 
```
\frac{}{}
\_{}
\^{}
\sqrt{}
etc... 
```

Its just a small change but it would make it easier when you write your latex symbol and it creates these curly braces when you press the spacebar and after that puts the cursor right into them. 

Don't know if its that good in practice but it seems like a good addition to your really good Plugin! I know that there is the other one but that would make it more simple for me.

**Comment by joeyuping** [comment]
@Fl1tzi  Thank you!

I have added the custom shorthand function into the plugin 1.4.0!
