### ISSUE TITLE
Feature request : More than 2 letters for custom shorthand

### ISSUE THREAD

**Issue by Elaws** [joeyuping/quick_latex_obsidian#30]
Hello,

First of all, thanks for this wonderful plugin, it is so useful.

It would be really nice if we could use whatever expression we wish as custom shorthands (= not limited by only two characters).

Thank you !

**Comment by joeyuping** [comment]
@Elaws  Hi! 

Thank you so much for the great suggestion! I have incorporated this in the new release, please take a look~

**Comment by Elaws** [comment]
@joeyuping : Thanks so much for taking this into account ! It works really well.

You may want to update the associated text in the settings (*Use two letters custom shorthands*) ;)
