### ISSUE TITLE
Feature request : Custom shorthands with multiple parameters {}

### ISSUE THREAD

**Issue by Elaws** [joeyuping/quick_latex_obsidian#31]
Hello,

In custom shorthands, if the expression ends by {}, cursor automatically goes inside the brackets. If there are multiple {}, it would be really useful that :

1. Cursor moves into the first `{}`, and not the last.
2. Using `tab`, we could jump to the next `{}`.
3. Using `shift + tab`, we could jump to the previous `{}`.

This feature exists in TexMaker (customize completion), and it is so useful.

I often define macros with multiple parameters (e.g. : `\macroName{param1}{param2}{param3}`) : it would be really useful to have the previously described feature.

Also, as mentioned [here](https://github.com/joeyuping/quick_latex_obsidian/issues/30), it would be wonderful if custom shorthands were not limited to only 2 characters.

Thanks !

**Comment by Elaws** [comment]
To anyone it may help, here is a solid workaround using Espanso :

https://forum.remnote.io/t/using-espanso-a-text-expander-to-automate-writing-latex/4089

**Comment by joeyuping** [comment]
@Elaws  Hi! Thank you so much for the suggestion!

though, as people use this custom shorthand for various different purposes, I am afraid that the tab jumping feature may not generalize to other use cases... 

But you are more than welcome to fork this repository and customize to your own usage~ 

However, I incorporated your other suggestion about allowing more characters to be the custom shorthands. Hope that helps~

**Comment by Elaws** [comment]
Thanks for implementing #30 ! 

If this tab jumping function was proposed as an option disabled by default, wouldn't it be safe for, other use cases ?

If not applicable, I will think of forking the repo indeed ;)

**Comment by joeyuping** [comment]
Resolved in v2.3.0, please update and take a look! (try uninstall and reinstall the plugin to see the new default list of shorthands with multiple parameters)

The function now allows using "#cursor"  to set the cursor location after replacement, 
and also use "#tab" to set the next place to fill after pressing tab

e.g. bi:\\binom{#cursor}{#tab},  after keying bi and spacebar, the shorthand will expand into \\binom{|}{#tab} with cursor in the first brackets. After keying the values in first brackets, press tab to jump to the #tab location to continue typing.
