### ISSUE TITLE
Feature Request: Allow whitespace in custom shorthands

### ISSUE THREAD

**Issue by abhmul** [joeyuping/quick_latex_obsidian#35]
I was trying to create a custom command that involves whitespace at the end, but unfortunately, the space was cut off. This seems like it would be a simple modification of the code for parsing custom commands.

If you're interested in adding this to the repo, I can look into implementing it.

**Comment by mayurankv** [comment]
Having whitespace would definitely be very handy, I too would be interested in this!

**Comment by joeyuping** [comment]
Resolved in v2.3.0, please update and take a look!
