### ISSUE TITLE
Shortcut triggers outside of $$

### ISSUE THREAD

**Issue by Nixxen** [joeyuping/quick_latex_obsidian#36]
Problem: 
Typing "in" in a normal sentence (outside $$ brackets) will trigger the "\infty" keyword

Expected outcome: 
Typing "in" should only write "in" when outside of $$ brackets.

Notes:
Not sure why this happens, and it happens only occasionally and is related to the note it is typed in.
I can enter one note where this is a problem, type "in " and it converts to "\infty", switch to another where this is not a problem and it types "in " as I would expect. Switch back to the note with the problem and it again types "\infty" instead of "in ".

**Comment by Nemoos-0** [comment]
I had this issie too. I found out that in the note there was a `$$` that markdown interprets as an inline math that opens and closes, but this plugin reads it as a block math so it thinks you are in a math mode. Try to look for a `$$` in the file where the problem occour and delete it.

Hope it helped

**Comment by joeyuping** [comment]
yes indeed, an unused $$ somewhere at the front of the text may be the culprit.
