### ISSUE TITLE
Auto frac should not work inside text elements

### ISSUE THREAD

**Issue by rafaelurben** [joeyuping/quick_latex_obsidian#37]
The feature `Type "/" instead of \frac{}{}` does also trigger inside `\text{}` elements, which it should not because LaTeX doesn't support `frac` statements inside `text`.

![image](https://user-images.githubusercontent.com/48059688/156171920-d27cbfd6-9a4c-4177-81a4-f14ad55470f4.png)
![image](https://user-images.githubusercontent.com/48059688/156171968-7f925539-d074-4377-b169-e5c8c9fdc716.png)

**Comment by joeyuping** [comment]
Resolved in v2.3.0, please update and take a look!

**Comment by rafaelurben** [comment]
Thank you very much! Works like a charm 👌
