### ISSUE TITLE
Shortcut for Cases Block

### ISSUE THREAD

**Issue by ms20220221** [joeyuping/quick_latex_obsidian#38]
Hi!
The shortcut for Align block is quite convenient. Why not set a shortcut for Cases Block,too? For example,`Alt+Shift+C`.
Besides,it would be more than helpful if 'Enter' in Case Block will be automatically replaced by '\\+Enter'.
Thank you for this plugin!

**Comment by joeyuping** [comment]
Thank you for the great suggestion! will add that in the next version

**Comment by joeyuping** [comment]
Resolved in v2.3.0, please update and take a look!
