### ISSUE TITLE
Issue (or possible bug?) using the underscore _ after curly brackets {}.

### ISSUE THREAD

**Issue by mayurankv** [joeyuping/quick_latex_obsidian#42]
Hi, just want to say thank you so much for the plugin! It makes using obsidian for maths not only bearable but very flowing.

I have a slight issue which is after using curly brackets {} (for example $\vec{x}$), then using the underscore character _ creates a pair of underscores __ as I would expect in the normal obsidian editor but within the latex delimiters, I would expect just one _ to be inserted as it is when inserted after for example $x_$. This also creates an issue with the automatic enclosing of things following the underscore since where $x_2$ goes to $x_{2}$ and $\vec{x}_2$ goes to $\vec{x}_{2}$, with the double insertion and blindly typing onwards, $\vec{x}__$ goes to $\vec{x}_2_$ which goes to $\vec{x}_2}{_$ which is definitely not desired behaviour (and means one has to go back to fix the resulting mess breaking the flow of typing) nor can I see a ruleset which would cause this.

This would be completely solved by not pairing _ characters within the latex delimiters I believe!

**Comment by joeyuping** [comment]
hi @mayurankv ! 

sorry, I don't seem to be able to replicate the issue you are facing.
on my machine, typing \vec{x} followed by the underscore creates only one underscore.

**Comment by mayurankv** [comment]
Ah, it turns out that I had automatic pairing of markdown syntax (so _ and *) on in obsidian as a whole. I realised I never really use this feature outside math blocks anyway since I use Cmd I and Cmd B for italics and bold anyway so I've just turned it off and that now works for me! Thanks!
