### ISSUE TITLE
Feature Request: Possible custom bracket expansions

### ISSUE THREAD

**Issue by mayurankv** [joeyuping/quick_latex_obsidian#43]
A request that is pretty low priority (but may be easy to implement?), I was wondering if one could choose how brackets auto expand. I have defined paired delimeters for both square brackets and parenthesis (and others) and would ideally like the $(...)$ brackets to expand to my $\pbrac{...}$ instead of $\left(...\right)$. Could this be an option in settings?

In a similar vein, would auto expansion for other delimiters like \lver\rvert, \langle\rangle and \{\} be possible?

**Comment by joeyuping** [comment]
Hi!! 

sorry for the really late reply...

Now with custom shorthand, may I suggest employing the shorthand, may be in a form like below:

vb:::\lvert #cursor \rvert
ab:::\langle #cursor \rangle

or something along those lines?
add these to the shorthand parameter in the setting page.

**Comment by mayurankv** [comment]
Sorry, let me make myself a bit clearer. One of the settings in the plugin is for brackets to auto expand. For example, when you type `$(\frac{1}{2})$`, the brackets will auto expand to `$\left(\frac{1}{2}\right)$`. I would like to optionally have the brackets to expand to alternative delimiting pairs - in my case `$\brac{\frac{1}{2}}$`. So instead of the transformation `['(',')'] -> ['\left(','\right)']`, an optional custom transformation of `['(',')'] -> ['\brac{','}']`.
