### ISSUE TITLE
Superscript problem

### ISSUE THREAD

**Issue by Nemoos-0** [joeyuping/quick_latex_obsidian#45]
First things first, thanks for the awesome plugin, it is one of the main tools of my workflow.

After the last update, the superscript does not behave as expected: it keeps expanding the curly brackets even if they are already there

`a^b` → `a^{b}` → `a^{{b}}` → `a^{{{b}}}`

Thank you for your work and commitment 🙂.

**Comment by joeyuping** [comment]
@Nemoos-0 Thank you so much!  really sorry for the ugly error. Have resolved it in v2.3.1
