### ISSUE TITLE
Default List and New Shorthands not working

### ISSUE THREAD

**Issue by mayurankv** [joeyuping/quick_latex_obsidian#46]
Hi, thanks so much for the updates and the added functionality! I just wanted to note that in your default list, nu:\nu; reads as a newline character and results in two lines 'nu:' and 'u;'.

Also unfortunately, the new shorthands aren't working at all for me. Even with the basic list uninstalled and reinstalled, even expanding things like al:\alpha or sq:\sqrt{} doesn't work. Not quite sure why! Trying to expand $al$ by adding a space after al just results in $al $ unlike $\alpha$ as expected. Sorry about this, please do let me know if this could be an issue on my end!

**Comment by joeyuping** [comment]
@mayurankv thanks again! and thanks so much for correcting my English~ 

Please see v2.3.3
