### ISSUE TITLE
Superscript expansion still buggy

### ISSUE THREAD

**Issue by mayurankv** [joeyuping/quick_latex_obsidian#47]
Hi, I'm still seeing the issue regarding expansion of superscripts. i.e. x^2 becomes x^{2} as expected but pressing space again makes it x^{{2}} and this repeats.

**Comment by joeyuping** [comment]
sorry, do you happen to be using the legacy mode of obsidian? My bad, I didn't check the backward compatibility. Have resolved the issue. Please update to v2.3.3

**Comment by mayurankv** [comment]
Hi, I am indeed using the legacy editor (the text-snippets plugin I previously mentioned doesn't work perfectly in the new editor so stuck for now - though with the changes to your plugin, I may be able to get away from that plugin mostly!). Thank you for resolving!
