### ISSUE TITLE
Feature Request: <tab> to jump outside of brackets

### ISSUE THREAD

**Issue by dedekindcut** [joeyuping/quick_latex_obsidian#48]
Would it be possible to have a shortcut that allows you to quickly jump out of (), [], {}, ||, etc? Maybe use tab to jump to the next instance of a closing bracket so you don't have to press arrow keys and break your typing flow.

**Comment by mayurankv** [comment]
This would be a really great addition in my opinion!

**Comment by KALKI-the-avataar** [comment]
@dedekindcut also if no brackets are present then jump out of $/$$

**Comment by mayurankv** [comment]
Just another suggestion which I think could also be useful. When tabbing sometimes I tab too far, being able to shift tab backwards into brackets would be nice (especially as I don't want shift tab to carry out any indentation functionality when I'm in a latex block).

**Comment by joeyuping** [comment]
Hi all!!! 

Thanks so much for the great suggestions!

I have tried implementing the above tab and shift tab functions in v2.3.5. Please kindly take a look and see if its ok!
