### ISSUE TITLE
timing issue with auto-closing brackets

### ISSUE THREAD

**Issue by infinityiowastaken** [joeyuping/quick_latex_obsidian#5]
Hey!
I think I've found a minor bug in the auto-close logic:

when **autoclose square brackets** is enabled, pressing the `shift` key, then the `[` key (to type a `{` character), and then releasing `shift` before releasing the `[` will lead to the auto-complete adding a `]` after the `{`, which can cause some confusion

Thanks!

**Comment by joeyuping** [comment]
Thank you!! Will look into this issue asap. @infinityiowastaken

**Comment by joeyuping** [comment]
After much thinking, finally got a way to solve this issue! Please see version 1.5.0

Thank you!
