### ISSUE TITLE
[QoL] Please increase the text box size for custom shorthands

### ISSUE THREAD

**Issue by firinael** [joeyuping/quick_latex_obsidian#51]
Alternatively, let us edit shorthands in a dedicated file or something. The settings text boxes really aren't made for this.

**Comment by joeyuping** [comment]
Hi!

Thank you so much for bringing this up! I realise it was a type in the code, which I have resolved in v2.3.4 .  The text box for custom shorthand is now much bigger. Hopefully that should work better.
