### ISSUE TITLE
new line

### ISSUE THREAD

**Issue by secchipietro04** [joeyuping/quick_latex_obsidian#53]
how do i go to new line?
I tried \\ \ \n \newline but nothing.
thanks

**Comment by joeyuping** [comment]
Hi! 
Sorry, I am not really sure what you mean.
A new line in obsidian simply needs to press enter.
or do your require a newline in any specific place?

for multi-line latex, use double dollar sign to enclose the expression:

$$
your latex
it can have multi-line, just press enter
$$

might this be what you need?

**Comment by julianmueller** [comment]
there is no multiline in latex math. You'd need an environment for that. Like `\begin{matrix}\end{matrix}` or `array` or `cases`.
But this is not related to this plugin.
