### ISSUE TITLE
Feature request: Only enable plugin features when in-between $ symbols

### ISSUE THREAD

**Issue by laur-ns** [joeyuping/quick_latex_obsidian#54]
It's really annoying when I want to make something bold with \_\_this\_\_ but pressing space automatically appends a curly bracket after it.

Also annoying when you want to type the word 'up ' but instead it changes to \upsilon. I've disabled the shorthand but it would be much better if it only works inside $$ and not outside of it.

**Comment by joeyuping** [comment]
Hi @laur-ns ,

I am sorry, but I could not replicate the issue you have mentioned. 
These two functions you mentioned only fires when the cursor is enclosed by a single dollar sign $ or double dollar sign $$. 

Might you have an empty double dollar sign $$ some where in your text? when that happens, the plugin will think that the rest of the text after the double dollar sign $$ are all within the multiline latex, and so these functions will fire.

If possible, please kindly try typing in a brand new document and see if the issue still persist? 

Thank you!

**Comment by laur-ns** [comment]
Omg you're right, after searching for a while it turns out there was an extra $ that I added. Sorry about that, and thank you for this plugin!
![Screenshot 2022-06-12 032032](https://user-images.githubusercontent.com/80611334/173194028-cfb9873e-5b73-4464-b41f-faf310cc6c7d.png)

**Comment by joeyuping** [comment]
@laur-ns    Thank you! Really hope the plugin is useful to you :)
