### ISSUE TITLE
cursor not working properly

### ISSUE THREAD

**Issue by julianmueller** [joeyuping/quick_latex_obsidian#57]
Hi,
in latest update of the shorthands there are these two tips:

>**Tip2**: Use "#cursor" within snippet to set the cursor position after replacement
>**Tip3**: Use "#tab" within snippet for cases of multiple parameters. e.g. bi:\binom{#cursor}{#tab}, after keying bi and spacebar, the shorthand will expand into \binom{|}{#tab} with cursor in the first brackets. After keying the values in first brackets, press tab to jump to the #tab location to continue typing.

But this does not work properly. I used the example `bi:\binom{#cursor}{#tab}` but the autocomplete made `\binom{#{#tab}`. Id same goes for this example: `cs:\cos(#cursor);` -> `\cos(#`.

Still a great plugin tho!

**Comment by joeyuping** [comment]
Hi !

Thank you! 
However, I am not so sure whether it was version difference or... as I am unable to replicate the situation as you mentioned.... Does the problem still persist?

**Comment by julianmueller** [comment]
Hi,
i just updated to the latest version of your plugin, and unfortunately, the bug still exists for me. I disabled all other plugins and styles and tried with only one shorthand command in config file, but no luck. I also tried turning off all other settings for your plugin.

eg with the suggestion from #58, i get (`[SPACE]` means the keystroke):

`vmat:\begin{vmatrix}#cursor\end{vmatrix};`
`$$\vmat[SPACE]$$` -> `$$\begin{vmatrix}#end{vmatrix}$$`

I dont know why this happens.

**Comment by julianmueller** [comment]
sorry to say... but the TAB and ENTER in not working for me, for the listed matrix types... :(

**Comment by joeyuping** [comment]
oh!!

I found the issue! Please try v2.3.6
