### ISSUE TITLE
Auto close | | (absolute value)

### ISSUE THREAD

**Issue by Yoav6** [joeyuping/quick_latex_obsidian#60]
It would be nice to have the vertical line | work like brackets, so when you type it another one is immediately created and your cursor will be place between them, and if you select an expression an type | it would enclose the selection instead of deleting it.

**Comment by joeyuping** [comment]
Thank you so much for the suggestion!

However, as the | symbol is also used very commonly in the conditional probability context (e.g.  P(x|y) ) , I am afraid that having this function may affect this other usage.

**Comment by Yoav6** [comment]
That's a good point! I think if it is toggle-able then we could have best of both worlds - If you work with lots of absolute values, turn it on. If you work with conditional probability or anything that uses singular |, turn it off. And the default could be either mode.
