### ISSUE TITLE
Feature Request: Auto replace only in math mode, i.e. double $

### ISSUE THREAD

**Issue by adkiem** [joeyuping/quick_latex_obsidian#62]
Hello,

I really like your plugin. But is there a way to make it replace my typing only in math mode?
For example me typing: "From IID distribution/MLE to L2-Norm" triggers auto fraction and "could be handy" triggers custom shorthand for \beta and so on.

best regards!

**Comment by joeyuping** [comment]
hi !

already, those functions you mentioned should only work when in math mode, meaning when in between either single $ signs or double $ signs.

could you kindly help check if you might have any dangling $ in your earlier text? or, try opening a new document and try if the condition still exist?

**Comment by adkiem** [comment]
Hey,

I checked and you were somewhat right. I had two formulas behind each other like so: „$...$$…$“ (without quotation).
Having no closing double dollars seems to have got it confused. Putting a space in-between ($…$ $…$) solved the issue.

Thanks for the hint!

**Comment by joeyuping** [comment]
I see ~ ok ok ! thanks ~
