### ISSUE TITLE
Turn off replacing brackets

### ISSUE THREAD

**Issue by Fabienvg** [joeyuping/quick_latex_obsidian#65]
For example, when I want to type: $x_{(i)}$, I would first type x_(i) and then hit space to get x_{(i)}, however, after hitting space I get x_{i}. It removes the brackets ().

Maybe a setting for toggling on and off this functionality would be a nice addition for your plugin.

**Comment by joeyuping** [comment]
Hi! @Fabienvg 

Really sorry for the extremely late reply... I have updated the plugin to NOT replace the round brackets when the string in between the brackets are less than 3 characters. I hope this may serve the purpose you mentioned? (mostly for indexing I presume?)

Hope this works~
