### ISSUE TITLE
Auto placement of "\\" and "&" on enter within the enabled shortcut blocks

### ISSUE THREAD

**Issue by fvcci** [joeyuping/quick_latex_obsidian#68]
If I have the align, matrix, or cases shortcut blocks enabled I get the characters "\\\\" and "&" automatically placed on an enter while I am in the corresponding block:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/71908175/193356106-ce63a88d-1452-4d3c-879b-97518f930594.png">

As you can see on enter it places a "\\\\" on the current line then skips an indentation and places a "&" immediately after. But a lack of indentation is not my main complaint. It may be convenient to automatically place these characters on enter, but in many cases this may not be what a user wants. 

On the first line I have an overly long line in the code, so I would want it to be in typed in separate lines. But when it is being displayed I want it to be in one line since it can fit in one line. Adding the "\\\\" on enter makes it so that a user would have to delete them every time their code is too long but when it is being displayed it would not be.

On the last line I want to display the variable again to show that I am square rooting both sides. This would be a common reason to display the left hand side to an equation, and with the auto placement of "&" it is inconvenient to do because it must be deleted to get the alignment correct.

There are many other reasons to why the auto placement is inconvenient other than these, which is why I think this feature should be removed or separated from the functionality of shortcut blocks because I think shortcut blocks are really useful and I would use them if it weren't for "\\\\" and "&".

**Comment by joeyuping** [comment]
Hi @fvcci !

Thank you so much for the suggestion!
I did some modification to the functionality (see v2.4.0)
- user can now set whether to use enter or shift-enter within align and cases block to automatically add next line symbols \\. (see settings page)  NOTE: the & symbol will no longer be automatically added after pressing enter, but an additional function for alignment is added (see next)
- **new function**: when within align block, the plugin automatically add align symbol "&" before user-defined symbols (default: = > < \\le \\ge \\neq \\approx)
e.g. x =(press "space" here), and "&" will be added before the = sign.
- when at the end of the align, matrix or cases block, pressing "tab" once (for align) or twice (for matrix and cases block) will bring the cursor out of the block.
- If next line is $$, press "tab" again will jump out of $$.

I hope the above changes would improve the workflow for the use case you mentioned above. Thank you!
