### ISSUE TITLE
Replacing only in math mode

### ISSUE THREAD

**Issue by bartlomiejnowak94** [joeyuping/quick_latex_obsidian#72]
I see the similar problem to that [#62](https://github.com/joeyuping/quick_latex_obsidian/issues/62) still is the thing. When I type in regular text and press the space, the plugin replace the word with the shorthand rule, for example:

in -> \infty

I love this plugin, but this drive me nuts! I want to do it only in math mode

**Comment by joeyuping** [comment]
Hi! @bartlomiejnowak94 

It is already the case that the plugin  custom shorthand function should only fire when the cursor is within math environment.

please kindly see if there may be any dangling $ sign that is not closed in the preceding text? or please kindly see if the issue actually arise when typing in a new blank note?

thank you!

**Comment by bartlomiejnowak94** [comment]
Right now, behavior is correct. Great :) It works both in blank note like in regular filled with text and math modes :)
