### ISSUE TITLE
Custom Shorthand Paramter :

### ISSUE THREAD

**Issue by Dr4kn** [joeyuping/quick_latex_obsidian#77]
I would like that : could be used in shortcuts. 
Encasing the shortcut between two symbols (like ") would make this possible. 
Maybe a toogle where one can choose which symbol encases the shortcuts in the written dialog, so that it isn't a breaking change.

like: 
```
":~~":\approxcolon;
"<=":\le;
```

**Comment by joeyuping** [comment]
Hi @Dr4kn !

My sincere apology for the really late update!

Please kindly see v2.6.1, where I changed the delimitter to ":::" instead of ":". This should then allow the ":" symbol whether as the keyword or the snippet. 
However, please do make sure to first change all existing ":" to ":::" first.
