### ISSUE TITLE
Feature Ehanced Request: Use Tab to Expand Snippets

### ISSUE THREAD

**Issue by langshangyuan** [joeyuping/quick_latex_obsidian#80]
Currently the plugin is quite awesome, it brazlingly boosts my speed of writing latex math equaiton in Obsidian. In other editors, we tend to use the tab key to expand pre-defined snippets. I dream to keep this behavior consistent between different applications.

Hope you can add the option which allows user to expand the snippets using tab key. (Although I know, there are some undesired outcome when you press tab under different situation.😂)

Thank you for your awesome plugin again!!!

**Comment by langshangyuan** [comment]
An additional suggestion, if user delete the first `$` symbol, the following `$` will automatically be deleted.

**Comment by joeyuping** [comment]
thank you for the great suggestion!! give me some time

**Comment by Catyre** [comment]
Any updates on this change?  Found this thread after my own wishing for tab-completing of snippets rather than using space (a lot of the time, I really do mean to use 'space').

Great job on the plugin, I started using it today and so far it's been great!

**Comment by joeyuping** [comment]
Hi @Catyre @langshangyuan 

Really sorry for the late update!!
Please see v2.6.1. A setting toggle has been added to allow the use of TAB for autocompletion. 

Deletion of $ symbol as a pair has also been added. @langshangyuan 

Thanks!
