### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by guin0x** [joeyuping/quick_latex_obsidian#81]
Hi, first of all I would like to say that this is GODLIKE! Before I was using AutoKey from Ubuntu to have some macros but this is just much much better...

I would like to know if its possible to, instead of writing "te" followed by SPACE-BAR to get `\text{}` if it would be possible to add the pressing of the TAB, instead of SPACE-BAR, to "autocomplete" the thing? I say this because from a programming background I believe most users are used to pressing TAB to autocomplete something, so while using this AMAZING plugin, I keep on pressing "te" followed by a TAB instead of the SPACE-BAR to generate the `\text{}` that I want.

Once again thanks for your work, it's really appreciated.

**Comment by joeyuping** [comment]
thank you for the suggestion ! give me some time

**Comment by joeyuping** [comment]
Thank you, and my sincere apology for the really late update!

please see v2.6.1. A setting toggle was added to allow the use of TAB for autocompletion~
