### ISSUE TITLE
\left| \right| can't be rendered correctly in some cases.

### ISSUE THREAD

**Issue by CMBill** [joeyuping/quick_latex_obsidian#82]
If I use `$$\left| \right|$$` to write a fraction inside the absolute, the absolute value symbol won't be rendered.

Just like this: 
![图片](https://user-images.githubusercontent.com/51294526/210089754-014bb838-34f4-45cf-ba21-16427d6c7ba8.png)

The desired equation should be like this:
![](https://latex.codecogs.com/svg.image?\left|&space;\frac{a}{b}&space;\right|)

If the equation inside the `$$\left| \right|$$` is not a fraction, the rendering is correct, like this:
![图片](https://user-images.githubusercontent.com/51294526/210089686-678a192f-fe8b-49c5-a1a2-4796313d9a0f.png)

If I use `$$\lvert \rvert$$` or just a couple of `|`, the height of the bars between the fraction won't be the same as the fraction.

**Comment by CMBill** [comment]
The vertical bar in`\bigg|` won't be rendered either.

**latex code:**
`$$f'(z_{0}) = \frac{\mathrm{d}w}{\mathrm{d}z}
\bigg|_{z = z_0}$$`

**The desire equation**

$$f'(z_{0}) = \frac{\mathrm{d}w}{\mathrm{d}z}
\bigg|_{z = z_0}$$

**What I actually see in Obsidian**
![图片](https://user-images.githubusercontent.com/51294526/210915020-117bf44c-a317-4024-b2c0-f0edfcd1b5d3.png)

**Comment by joeyuping** [comment]
Hi ! @CMBill 

Thank you for bringing this up~

Sorry, however, I was not able to replicate the issue you mentioned. The vertical bars rendered correctly on my obsidian:

![image](https://user-images.githubusercontent.com/75552068/210916905-5fde1b7e-076b-4c06-81a9-f879ed6c7b56.png)

Also, I was wondering if the issue you are facing may be related to obsidian as a whole, and not so much the problem of the quick latex plugin? If the issue persist, you might like to post the problem to the obsidian team instead?

**Comment by CMBill** [comment]
Thanks to your reply!

I have checked my Obsidian vault. After resetting it the formulars are redered correctly.
