### ISSUE TITLE
Is it support feature like \overline ?

### ISSUE THREAD

**Issue by jokervTv** [joeyuping/quick_latex_obsidian#83]
I wonder that how write \overline rightly, it is not work with $$ \overline{a \cdot b} $$

Thanks for your reading.

**Comment by joeyuping** [comment]
Hi! @jokervTv 

Sorry for the late reply!
It seems that this is an upstream problem on mathjax itself. The overline is actually there, it is just not visible. Try zooming in and you might be able to see it. 

Kindly refer to this other tread:
[](https://forum.obsidian.md/t/overline-not-working-in-latex-math-mode/12486)
