### ISSUE TITLE
Bug: Tabout and general tab not working for equations on list elements

### ISSUE THREAD

**Issue by StrangeGirlMurph** [joeyuping/quick_latex_obsidian#84]
!!! Start reading [here](https://github.com/joeyuping/quick_latex_obsidian/issues/84#issuecomment-1399553565) !!!

I would love to be able to tab or enter out of equations.
Always reaching for the arrow key at the end of an equation is super slow.
I never use tab in an equations. I think it would be the best option.

Sadly I don't know how obsidian plugins work yet and don't really know your code base...
I would just make a PR if I knew. But it shouldn't be that hard to implement for you.
Obsidian-latex-suite has this feature already implemented. Their tabout:
> 
    - Pressing Tab while the cursor is at the end of an equation will move the cursor outside the $ symbols.
    - Otherwise, pressing Tab will advance the cursor to the next closing bracket: ), ], }, >, or |.

https://github.com/artisticat1/obsidian-latex-suite#tabout

Here is their source code:
+ https://github.com/artisticat1/obsidian-latex-suite/blob/main/src/main.ts#L348-L381
+ https://github.com/artisticat1/obsidian-latex-suite/blob/main/src/main.ts#L757-L824
+ https://github.com/artisticat1/obsidian-latex-suite/blob/main/src/main.ts#L869-L884

**Comment by StrangeGirlMurph** [comment]
On another note: Thank you for your incredible plugin! 
I really appreciate your work :)

**Comment by StrangeGirlMurph** [comment]
Now I understood that I found a bug ^^
The tabout doesn't work when the equation is an item of a list (bullet or numbered).

Example:
`+ Let $a' \in G$`

**Comment by StrangeGirlMurph** [comment]
Tab in general doesn't work on list items.
That's also the reason that shorthands like `bi:\binom{#cursor}{#tab};` also doesn't work

**Comment by joeyuping** [comment]
Hi! @StrangeGirlMurph 

My deepest apology for the really late reply... 
Thank you for bringing this up! Though, while I tested the tabout for equation in list item, it does work fine.
Does this problem still exist on your end?

**Comment by StrangeGirlMurph** [comment]
Oh don't worry. I actually switched to the latex suite plugin now (and have actually been working on it).
You're right! The bug disappeared :) Those are my favorite bugs! Thank you :)
