### ISSUE TITLE
\$ should not produce \$$, right?

### ISSUE THREAD

**Issue by lebigot** [joeyuping/quick_latex_obsidian#85]
As far as I understand, because two `$` on a line are interpreted as LaTeX code, entering the dollar (currency) sign as `\$` is a good practice.

Now, this means that it would be useful that `\$` do not result in `\$$` (but simply in `\$`). Would this make sense?

**Comment by joeyuping** [comment]
Thank you! @lebigot  Indeed thats really reasonable. I will include that in the next update.

and sorry for the late reply!

**Comment by joeyuping** [comment]
Hi! @lebigot please see update 2.6.1

**Comment by lebigot** [comment]
This works for me, thanks a lot!
