### ISSUE TITLE
Auto-close after space doesn't work on Android

### ISSUE THREAD

**Issue by CopperSulph8** [joeyuping/quick_latex_obsidian#87]
On pressing `space`, autoclosing doesn't seem to work on Android on any keyboard. It seems this is an Android specific issue with detecting space keypresses as changing the code to, for example, `key:';'` instead of `key:'Space'` seems to fix the issue. Although it would be great for this to work properly.

**Comment by joeyuping** [comment]
Hi!

I am sorry, but this plugin does not work on mobile in general right now. It was a little beyond my knowledge. If there are any friends out there familiar with how codemirror works on android or any other mobile platform, please feel free to fork this repo and share with everyone :)

**Comment by abhmul** [comment]
Having this work on android would be very useful to me. Hopefully someone who has a good understanding of android will come by and make this feature work. It seems like the issue may only need a minor change, judging by the fact other autocomplete keypresses work.
