### ISSUE TITLE
Plugin breaks on a specific string

### ISSUE THREAD

**Issue by BhavikDodda** [joeyuping/quick_latex_obsidian#93]
The plugin breaks when typing anything after "^{A}_{Z}X" wrapped inside "$$" and crashes obsidian.

**Comment by joeyuping** [comment]
Hi @BhavikDodda ! Thank you so much for bringing this up!

However, I was not able to replicate the issue. Typing "^{A}_{Z}X" wrapped inside "$$" obtains the following for me:
![symbol](https://user-images.githubusercontent.com/75552068/236630697-ae27016c-778f-4089-a4b6-0b4ecbd714fe.jpg)

Might you be using a different keyboard layout?

**Comment by BhavikDodda** [comment]
Yeah, I was using a different keyboard layout

**Comment by joeyuping** [comment]
Hi @BhavikDodda !

I see. I am sorry, but it seems for now the plugin could only work with the English keyboard layout.
