### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by KrispyKreme1195** [joeyuping/quick_latex_obsidian#95]
Is there any existing support for denoting quantities as a vector within an equation definition, or support for doing so? For example, in the equation to describe coulombs law as it applies to the forces exerted by a pair of charged points along a given direction vector uses bar/arrow notation to specify that F is a vector quantity and also can use the 'hat' notation to indicate the direction vector is of unit length.

**Comment by joeyuping** [comment]
Hi! @KrispyKreme1195 

These might be what you are looking for:
$\bar{F}$
$\overrightarrow{F}$
$\hat{F}$

You can search for "latex" or "mathjax", for example "latex hat", to get the code required of the math symbol you may need :)  All the best!
