### ISSUE TITLE
Autoclose $ not working.

### ISSUE THREAD

**Issue by kaevm** [joeyuping/quick_latex_obsidian#96]
When I type $, it doesn't autoclose, and I cannot find a setting for it in the plugin. Am I missing something obvious?

**Comment by joeyuping** [comment]
Hi! @kaevm 

This autoclose function should work by default. It can also be toggled in the plugin settings page:
![image](https://github.com/joeyuping/quick_latex_obsidian/assets/75552068/c44c0195-c46a-478e-be44-bbf5a4338afa)

Have you enabled the plugin? After installation, you may need to enable it by clicking here:

![image](https://github.com/joeyuping/quick_latex_obsidian/assets/75552068/855c244d-d705-4377-91d5-a1e69ef81de4)
