### ISSUE TITLE
double loop integral(and multiple loop integral) seems to be not supported yet.

### ISSUE THREAD

**Issue by lingkerio** [joeyuping/quick_latex_obsidian#97]
It looks like double (and multiple)  loop integration is not supported yet, but it's really common. Hope to be supported soon
<img width="464" alt="image" src="https://github.com/joeyuping/quick_latex_obsidian/assets/112792583/6aaa8617-d75a-4013-a942-feba5f5349f1">

**Comment by joeyuping** [comment]
Hi! @lingkerio 

This has to do with Obsidian itself. From my understanding, Obsidian uses Mathjax for math rendering, which does not currently supports double or multiple loop integral.

I did found a link that suggest some work arounds : []( https://math.meta.stackexchange.com/questions/9973/how-do-you-render-a-closed-surface-double-integral)

Hope this help!

**Comment by mayurankv** [comment]
I'm interested in these workarounds! I unfortunately can't see the link right now. Was it possibly not attached?

**Comment by lingkerio** [comment]
> Hi! @lingkerio 
> 
> This has to do with Obsidian itself. From my understanding, Obsidian uses Mathjax for math rendering, which does not currently supports double or multiple loop integral.
> 
> I did found a link that suggest some work arounds : https://math.meta.stackexchange.com/questions/9973/how-do-you-render-a-closed-surface-double-integral
> 
> Hope this help!

Thanks! It's very beneficial for me!

**Comment by mayurankv** [comment]
Also hopefully Mathias will come packaged with these soon aka [this PR](https://github.com/mathjax/MathJax-src/pull/923).
